version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adm
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: npm run dev
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    # command: sleep infinity
    depends_on:
      - web
